version: '3'
services:
  master_agent:
    build: ./master_agent
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - agent1
      - agent2
    networks:
      - app-network

  agent1:
    build: ./agent1
    ports:
      - "5001:5001"
    networks:
      - app-network

  agent2:
    build: ./agent2
    ports:
      - "5002:5002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge